language: ruby

rvm: 1.9.3

cache: bundler

env:
  - BUNDLE_PATH=$GEM_HOME

branches:
  except:
    - master

before_script:
  - printenv | sort
  - ls -la $GEM_HOME/*
  - ls -lar ${BUNDLE_PATH:-vendor/bundle}/*

script:
  - gem list
  - octopress deploy

