# Site settings
title: Parallel-in-Time
email: daniel.ruprecht@usi.ch
author: "Parallel-in-Time Enthusiasts"
description: ""
baseurl: ""
url: "http://parallelintime.org"
subscribe_rss: 'feed.xml'

root: /
permalink: /news/:year/:month/:day/:title/
code_dir: downloads/code
category_dir: news/categories
markdown: kramdown
permalink: news/:year/:month/:day/:title.html

timezone: UTC
encoding: utf-8

excerpt_separator: '<!--more-->'

sass:
  sass_dir: _sass
  style: :compressed

category_title_prefix: ""

collections:
  events_upcoming:
    output: true
  events_past:
    output: true
  groups:
    output: true
  projects:
    output: true
  methods:
    output: true
  codes:
    output: true

google_analytics_tracking_id: UA-62723342-1
