# Site settings
title: Parallel-in-Time
email: daniel.ruprecht@leeds.ac.uk
author: "Parallel-in-Time Enthusiasts"
description: ""
baseurl: ""
url: "http://parallelintime.org"

markdown: kramdown

exclude:
  - vendor/
  - travis_deploy_rsa.enc
  - travis_deploy_rsa.pub
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTORS
  - CONTRIBUTING.md

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-feed
  - jekyll/scholar
  - jekyll-sitemap

paginate: 5
paginate_path: "/news/page:num/"

timezone: UTC
encoding: utf-8

excerpt_separator: '<!--more-->'

assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: '/assets'
  assets:
    - '*.png'
    - '*.jpg'
    - '*.jpeg'
    - '*.svg'
    - '*.woff'
    - '*.woff2'
    - '*.eof'
    - '*.ttf'
  digest: true
  features:
    liquid: false
    automatic_img_size: false
    automatic_img_alt: false

collections:
  events_upcoming:
    output: true
  events_past:
    output: true
  groups:
    output: true
  projects:
    output: true
  methods:
    output: true
  codes:
    output: true
  pint2016:
    output: true

scholar:
  bibtex_filters:
    - latex
    - markdown

  style: ieee-with-url
  locale: en

  sort_by: year, authors
  order: ascending

  source: ./_bibliography
  bibliography: pint.bib
  bibliography_template: reference

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

google_analytics_tracking_id: UA-62723342-1
