name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo [[ $GITHUB_CONTEXT == *"food for bibbot"* ]]
        id: updater
