name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        if:  contains( github.event.issue.labels, 'food for bibbot' )
        run: |
          echo "YES!"
        id: updater
