name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        if: toJson(github) == *"food for bibbot"*
        run: |
          echo "YES!"
        id: updater
