name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - env:
          LABELS: ${{ github.event.issue.labels }}
      - name: testing
        run: |
          for i in $LABELS;
            do
              echo $i
            done
        id: updater
