name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    if:  contains( toJson(github), 'food for bibbot' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        run: |
          echo "YES!"
        id: updater
