name: Testing
on:
  issues:
    types: [labeled]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        run: |
          for i in ${{ github.event.issue.labels }}[@];
            do
              echo $i['name']
            done
        id: updater
