name: Testing
on:
  issues:
    types: [labeled]
jobs:
  test:
    # if: contains( toJson(github), 'noooo' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: testing
        run: |
          echo "YES!"
        id: updater
